version: "2"

services:
  dbserver:
      image: postgres:latest
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=tododb
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin